CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("contact-us/", include("contact.urls")),
    path("lead/", include("lead.urls")),
    path("client/", include("client.urls")),
    path("team/", include("team.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/urls.py
from django.urls import path

from client import views


app_name = "client"

urlpatterns = [
    path("", views.ClientListView.as_view(), name="clientList"),
    path("create/", views.ClientCreateView.as_view(), name="clientCreate"),
    path("<int:pk>/upload/", views.ClientDetailFileView.as_view(), name="clientUpload"),
    path("<int:pk>/detail/", views.ClientDetailView.as_view(), name='clientDetail'),
    path("<int:pk>/update/", views.ClientUpdateView.as_view(), name="clientUpdate"),
    path("<int:pk>/delete/", views.ClientDeleteView.as_view(), name="clientDelete"),
    path("export/", views.ClientExportView.as_view(), name="clientExport"),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("about-us/", views.about_us, name='about_us'),
]

lead/urls.py
from django.urls import path

from lead import views

app_name = "lead"

urlpatterns  =[
    path("create/", views.LeadCreateView.as_view(), name="leadCreate"),
    path("export/", views.LeadExportView.as_view(), name="leadExport"),
    path("", views.LeadListView.as_view(), name="leadList"),
    path("<int:pk>/detail/", views.LeadDetailView.as_view(), name="leadDetail"),
    path("<int:pk>/update/", views.LeadUpdateView.as_view(), name="leadUpdate"),
    path("<int:pk>/delete/", views.LeadDeleteView.as_view(), name="leadDelete"),
    path("<int:pk>/upload/", views.LeadDetailFileView.as_view(), name="leadUpload"),
    path("<int:pk>/convert-to-client", views.ConvertToClient.as_view(), name="leadToClient"),
]

team/urls.py
from django.urls import path

from team import views

app_name = "team"

urlpatterns  =[
    path("create/", views.TeamCreateView.as_view(), name="teamCreate"),
    path("", views.TeamListView.as_view(), name="teamList"),
    path("<int:pk>/detail/", views.TeamDetailView.as_view(), name="teamDetail"),
    path("<int:pk>/update/", views.TeamUpdateView.as_view(), name="teamUpdate"),
    path("<int:pk>/delete/", views.TeamDeleteView.as_view(), name="teamDelete"),
]

templates/base/base.html
<!doctype html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'main.min.css' %}">
  {% block css %}
  {% endblock %}
</head>
<body>
    {% include "base/navbar.html" %}
    {% include "base/messages.html" %}

    {% block body %}
    {% endblock %}

    
    {% include "base/footer.html" %}
    {% block js %}
    {% endblock %}

</body>
</html>

templates/base/footer.html
<footer class="py-8 text-center bg-violet-400 sticky left-0 bottom-0 w-full">
    <p class="text-xs text-black-700">Copyright (c) 2023 - Ishan CRM</p>

</footer>

templates/base/messages.html
{% if messages %}
<div class="px-6 py-6">
    {% for message in messages %}
        <div class="py-4 px-4 bg-violet-400 rounded-xl text-white">
            {{message}}
        </div>
    {% endfor %}
</div>
{% endif %}

templates/base/navbar.html
<nav class="py-6 flex px-6 sticky top-0 justify-between bg-violet-400">
    <div class="space-x-4">
        <a href="{% url 'core:index' %}" class="text-white">Ishan CRM</a>
        {% if user.is_authenticated %}
        <a href="{% url 'dashboard:dashboard' %}" class="text-white">Dashboard</a>
        <a href="{% url 'team:teamCreate' %}" class="text-white">Create Team</a>
        <a href="{% url 'team:teamList' %}" class="text-white">Teams</a>
        <a href="{% url 'lead:leadList' %}" class="text-white">Leads</a>
        <a href="{% url 'client:clientList' %}" class="text-white">Clients</a>
        {% endif %}
    </div>

    <div class="space-x-4">
        <a href="{% url 'contact:contact_us' %}" class="text-white">Contact Us</a>
        <a href="{% url 'core:about_us' %}" class="text-white">About Us</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'accounts:profile' %}" class="py-4 px-6 bg-violet-600 rounded-xl text-white">{{request.user.username|title}}</a>
        <a href="{% url 'accounts:logout' %}" class="py-4 px-6 bg-red-600 rounded-xl text-white">Logout</a>
        {% else %}
        <a href="{% url 'accounts:login' %}" class="py-4 px-6 bg-violet-600 rounded-xl text-white">Login</a>
        <a href="{% url 'accounts:signup' %}" class="py-4 px-6 bg-violet-300 rounded-xl text-white">Signup</a>
        {% endif %}
    </div>
</nav>