CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("contact-us/", include("contact.urls")),
    path("lead/", include("lead.urls")),
    path("client/", include("client.urls")),
    path("team/", include("team.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/urls.py
from django.urls import path

from client import views


app_name = "client"

urlpatterns = [
    path("", views.ClientListView.as_view(), name="clientList"),
    path("create/", views.ClientCreateView.as_view(), name="clientCreate"),
    path("<int:pk>/upload/", views.ClientDetailFileView.as_view(), name="clientUpload"),
    path("<int:pk>/detail/", views.ClientDetailView.as_view(), name='clientDetail'),
    path("<int:pk>/update/", views.ClientUpdateView.as_view(), name="clientUpdate"),
    path("<int:pk>/delete/", views.ClientDeleteView.as_view(), name="clientDelete"),
    path("export/", views.ClientExportView.as_view(), name="clientExport"),
]

client/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

from team.models import Team
# Create your models here.

User = get_user_model()


class Client(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="clients")
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="clients")
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("client:clientDetail", args=[self.id])

class Comment(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="client_comments")
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField(max_length=1000, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="client_comments")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Client comment by {self.created_by.username.title()}"

class ClientFile(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="client_files")
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name="files")
    file = models.FileField(upload_to="files/client/")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="client_files")
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Client file by {self.created_by}"

client/forms.py
from django import forms
from django.contrib.messages import error
from django.core.exceptions import ValidationError

from client.models import Client, Comment, ClientFile
from team.models import Team

class ClientUpdateForm(forms.ModelForm):
    team = forms.ModelChoiceField(Team.objects.all())

    def __init__(self, user, *args, **kwargs):
        super(ClientUpdateForm, self).__init__(*args, **kwargs)
        self.fields["team"].queryset = Team.objects.filter(created_by=user)
    class Meta:
        model = Client
        fields = ['name','email','description','team']


class ClientCreateForm(forms.ModelForm):
    team = forms.ModelChoiceField(Team.objects.all())
    def __init__(self, user, *args, **kwargs):
        super(ClientCreateForm, self).__init__(*args, **kwargs)
        self.fields["team"].queryset = Team.objects.filter(created_by=user)
        
    class Meta:
        model = Client
        fields = ['name','email','description','team']
    
    def clean_team(self):
        data = self.cleaned_data["team"]
        if data.plan.max_clients <= data.clients.count():
            raise ValidationError(f"Client Limit Reached for team: {data}")
        return data


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ['file']

client/views.py
from django.shortcuts import get_object_or_404, redirect, HttpResponse

import csv

from django.urls import reverse

from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.messages import success

from django.urls import reverse_lazy

from client.models import Client
from client.forms import ClientUpdateForm, ClientCreateForm, AddCommentForm, AddFileForm
# Create your views here.

class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    context_object_name = "clients"
    template_name = "client/clientList.html"

    def get_queryset(self):
        return Client.objects.filter(created_by=self.request.user)


class GetComment(DetailView):
    model = Client
    context_object_name = "client"
    template_name = "client/clientDetail.html"

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs["comment_form"] = AddCommentForm()
        kwargs["file_form"] = AddFileForm()
        return kwargs

    def get_queryset(self):
        return Client.objects.filter(created_by=self.request.user, pk=self.kwargs["pk"])

class PostComment(SingleObjectMixin, LoginRequiredMixin, FormView):
    model = Client
    form_class = AddCommentForm
    context_object_name = "client"
    template_name = "client/clientDetail.html"

    def get_queryset(self):
        return Client.objects.filter(created_by=self.request.user, pk=self.kwargs["pk"])
    
    def post(self, request, *args, **kwargs): # from SingleObjectMixin returns url paramater
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.client = self.object
        comment.team = self.object.team
        comment.created_by = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("client:clientDetail", args=[self.object.id])

class ClientDetailView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        view = GetComment.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostComment.as_view()
        return view(request, *args, **kwargs)


class ClientDetailFileView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        fileUpload = AddFileForm(request.POST, request.FILES)
        if fileUpload.is_valid():
            client = Client.objects.get(created_by=request.user, pk=self.kwargs["pk"])
            file = fileUpload.save(commit=False)
            file.created_by = request.user
            file.team = client.team
            file.client = client
            file.save()
            success(request, "Client file uploaded")
        return redirect("client:clientDetail", pk=self.kwargs['pk'])  

class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Client
    form_class = ClientUpdateForm
    template_name = "client/clientUpdate.html"
    success_message = "client updated successfully"

    def test_func(self):
        self.object = self.get_object()
        return self.object.created_by == self.request.user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = Client
    template_name = "client/clientDelete.html"
    success_url = reverse_lazy("client:clientList")
    success_message = "Client successfully deleted"

    def test_func(self):
        self.object = self.get_object()
        return self.object.created_by == self.request.user


class ClientCreateView(LoginRequiredMixin,SuccessMessageMixin, CreateView):
    form_class = ClientCreateForm
    template_name = "client/clientCreate.html"
    success_url = reverse_lazy("client:clientList")
    success_message = "New Client Created"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        """
        Passing authenticated user to the create form of client
        """
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs



class ClientExportView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        clients = Client.objects.filter(created_by=request.user)
        response = HttpResponse(
            content_type = "text/csv",
            headers = {
            "Content-Disposition":f"attachment; filename='{request.user.username}-clients.csv'",
            }
        )
        writer = csv.writer(response)
        writer.writerow(['Client', 'Description','Created by','Created at',"Modified at"])
        for client in clients:
            writer.writerow([client.name, client.description, client.created_by, client.created_at, client.modified_at])
        return response            
        

templates/client/clientCreate.html
{% extends "base/base.html" %}
{% load tailwind_filters %}
{% block title %}Create New Client{% endblock %}

{% block body %}
<div class="w-1/2 bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    <h1 class="text-2xl text-center mb-2">Create New Client</h1>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="py-4 px-8 bg-violet-400 text-white rounded-xl">Create</button>
    </form>
</div>
{% endblock %}

templates/client/clientDelete.html
{% extends "base/base.html" %}
{% block title %}Delete: {{client.name}}{% endblock %}

{% block body %}
<div class="w-1/2 bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    <h1 class="text-2xl text-center mb-2">Delete client: {{client.name|title }}</h1>
    <form method="post">
        {% csrf_token %}
        <p class="mt-4 font-semibold">Do you want to delete this client: {{client.name|title}}?</p>
        <button type="submit" class="py-4 px-8 bt-4 rounded-xl bg-violet-400 text-white">Delete</button>
    </form>
</div>
{% endblock %}

templates/client/clientDetail.html
{% extends "base/base.html" %}
{% load tailwind_filters %}
{% block title %}{{client.name}}{% endblock %}

{% block body %}
<div class="flex space-x-4 px-6 py-6">
    <div class="w-1/2">
        <div class="h-fit bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
            <h1 class="text-2xl text-center font-bold mb-3">
                {{client.name|title}}
            </h1>
            {% if client.description %}
                <p class="font-semibold">Description</p>
                <p>{{client.description}}</p>
            {% endif %}
        
            <p class="font-semibold">Team</p>
            <p class="mb-2">{{ client.team }}</p>
        
            <p class="font-semibold">Created At</p>
            <p class="mb-2">{{ client.created_at|timesince }} ago</p>
        
            <p class="font-semibold">Modified At</p>
            <p class="mb-6">{{ client.modified_at|timesince }} ago</p>
        
            <a href="{% url 'client:clientList' %}" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Back to List</a>
            <a href="{% url 'client:clientUpdate' client.id %}" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Update</a>
            <a href="{% url 'client:clientDelete' client.id %}" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Delete</a> 
        </div>
        <div>
            <div class="bg-violet-200 px-4 py-4 rounded-xl">
                <h1>Uploaded Files</h1>
            <ul>
                {% for file in client.files.all %}
                    <li><a href="{{file.file.url}}">File {{forloop.counter}} Download</a></li>
                {% endfor %}
            </ul>
            </div>
            <div class="bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
                <h1 class="text-2xl font-bold">Upload New file</h1>
                <form action="{% url 'client:clientUpload' client.pk %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{file_form|crispy}}
                    <button type="submit" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Upload</button>
                </form>
            </div>
        </div>
    </div>
    <div class="w-1/2">
        <div class="bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
            <h1 class="text-2xl font-bold">Comments</h1>
            {% for comment in client.comments.all %}
                <div class="flex justify-between bg-violet-300 py-4 px-4 rounded-xl m-1">
                    <div>
                        <p>{{comment.content}}</p>
                    </div>
                    <div>
                        <p>Created By: @{{comment.created_by|title}}, {{comment.created_at|timesince}} ago</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
            <h1 class="text-2xl font-bold">Add Comment</h1>
            <form method="post">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <button type="submit" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/client/clientList.html
{% extends "base/base.html" %}
{% block title %}List of Clients{% endblock %}

{% block body %}
<div class="w-3/4 bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    <div class="flex justify-between">
        <h1 class="text-2xl">List of Clients</h1>
        <div>
            <a href="{% url 'client:clientCreate' %}" class="py-4 px-6 bg-violet-600 rounded-xl text-white">Create Client</a>
        <a href="{% url 'client:clientExport' %}" class="py-4 px-6 bg-violet-600 rounded-xl text-white">Export Clients</a>
        </div>
    </div>
    <div class="mt-6 flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Email</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Team</p>
    </div>
    {% for client in clients %}
        <a href="{{ client.get_absolute_url}}">
            <div class="flex justify-between">
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{client.name}}</p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{client.email}}</p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{client.team}}</p>
            </div>
        </a>
    {% empty %}
    <p>There are no client in the database </p>
    {% endfor %}
</div>
{% endblock %}

templates/client/clientUpdate.html
{% extends "base/base.html" %}
{% load tailwind_filters %}
{% block title %}Update :{{client.name}}{% endblock %}

{% block body %}
<div class="w-1/2 bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    <h1 class="text-2xl text-center mb-2">Update lead :{{client.name|title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="py-4 px-8 bg-violet-400 text-white">Update</button>
    </form>
</div>
{% endblock %}