CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("contact-us/", include("contact.urls")),
    path("lead/", include("lead.urls")),
    path("client/", include("client.urls")),
    path("team/", include("team.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from django.urls import reverse_lazy
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("logout/", LogoutView.as_view(next_page=reverse_lazy("accounts:login")), name='logout'),
    path("", views.ProfileView.as_view(), name="profile"),
]

client/urls.py
from django.urls import path

from client import views


app_name = "client"

urlpatterns = [
    path("", views.ClientListView.as_view(), name="clientList"),
    path("create/", views.ClientCreateView.as_view(), name="clientCreate"),
    path("<int:pk>/upload/", views.ClientDetailFileView.as_view(), name="clientUpload"),
    path("<int:pk>/detail/", views.ClientDetailView.as_view(), name='clientDetail'),
    path("<int:pk>/update/", views.ClientUpdateView.as_view(), name="clientUpdate"),
    path("<int:pk>/delete/", views.ClientDeleteView.as_view(), name="clientDelete"),
    path("export/", views.ClientExportView.as_view(), name="clientExport"),
]

lead/urls.py
from django.urls import path

from lead import views

app_name = "lead"

urlpatterns  =[
    path("create/", views.LeadCreateView.as_view(), name="leadCreate"),
    path("export/", views.LeadExportView.as_view(), name="leadExport"),
    path("", views.LeadListView.as_view(), name="leadList"),
    path("<int:pk>/detail/", views.LeadDetailView.as_view(), name="leadDetail"),
    path("<int:pk>/update/", views.LeadUpdateView.as_view(), name="leadUpdate"),
    path("<int:pk>/delete/", views.LeadDeleteView.as_view(), name="leadDelete"),
    path("<int:pk>/upload/", views.LeadDetailFileView.as_view(), name="leadUpload"),
    path("<int:pk>/convert-to-client", views.ConvertToClient.as_view(), name="leadToClient"),
]

team/urls.py
from django.urls import path

from team import views

app_name = "team"

urlpatterns  =[
    path("create/", views.TeamCreateView.as_view(), name="teamCreate"),
    path("", views.TeamListView.as_view(), name="teamList"),
    path("<int:pk>/detail/", views.TeamDetailView.as_view(), name="teamDetail"),
    path("<int:pk>/update/", views.TeamUpdateView.as_view(), name="teamUpdate"),
    path("<int:pk>/delete/", views.TeamDeleteView.as_view(), name="teamDelete"),
]

templates/index.html
{% extends "base/base.html" %}
{% block title %}Ishan CRM{% endblock %}

{% block body %}
<div class="w-1/2 h-fit bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    {% if request.user.is_authenticated %}
    <h1 class="text-2xl m-3 text-center">Shortcuts</h1>
    <div class="flex flex-col justify-between item-center">
        <div class="m-6"><a href="{% url 'accounts:profile' %}" class="px-4 py-4 bg-violet-400 rounded-xl text-2xl m-3">Profile</a></div>
        <div class="m-6"><a href="{% url 'dashboard:dashboard' %}" class="px-4 py-4 bg-violet-400 rounded-xl text-2xl m-3">Dashboard</a></div>
        <div class="m-6"><a href="{% url 'team:teamList' %}" class="px-4 py-4 bg-violet-400 rounded-xl text-2xl m-3">Teams</a></div>
        <div class="m-6"><a href="{% url 'client:clientList' %}" class="px-4 py-4 bg-violet-400 rounded-xl text-2xl m-3">Clients</a></div>
        <div class="m-6"><a href="{% url 'lead:leadList' %}" class="px-4 py-4 bg-violet-400 rounded-xl text-2xl m-3">Leads</a></div>
    </div>
    {% else %}
    <h1 class="text-2xl">You must be Logged in to use the features of CRM</h1>
    {% endif %}
</div>
{% endblock %}