CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("contact-us/", include("contact.urls")),
    path("lead/", include("lead.urls")),
    path("client/", include("client.urls")),
    path("team/", include("team.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lead/urls.py
from django.urls import path

from lead import views

app_name = "lead"

urlpatterns  =[
    path("create/", views.LeadCreateView.as_view(), name="leadCreate"),
    path("export/", views.LeadExportView.as_view(), name="leadExport"),
    path("", views.LeadListView.as_view(), name="leadList"),
    path("<int:pk>/detail/", views.LeadDetailView.as_view(), name="leadDetail"),
    path("<int:pk>/update/", views.LeadUpdateView.as_view(), name="leadUpdate"),
    path("<int:pk>/delete/", views.LeadDeleteView.as_view(), name="leadDelete"),
    path("<int:pk>/upload/", views.LeadDetailFileView.as_view(), name="leadUpload"),
    path("<int:pk>/convert-to-client", views.ConvertToClient.as_view(), name="leadToClient"),
]

lead/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

from team.models import Team
# Create your models here.

User = get_user_model()


class Lead(models.Model):
    class LEAD_PRIORITY(models.TextChoices):
        LOW = "LOW", 'Low'
        MEDIUM = "MEDIUM", 'Medium'
        HIGH = "HIGH", 'High'

    class STATUS_LEAD(models.TextChoices):
        NEW = "NEW"
        CONTACTED = "CONTACTED", 'Contacted'
        WON = "WON", 'WON'
        LOST = "LOST", 'Lost'

    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="leads")
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="leads")
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    priority = models.CharField(max_length=6, choices=LEAD_PRIORITY.choices, default=LEAD_PRIORITY.LOW)
    status = models.CharField(max_length=9, choices=STATUS_LEAD.choices, default=STATUS_LEAD.NEW)
    converted_into_clients = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("lead:leadDetail", args=[self.id])


class Comment(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="lead_comments")
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField(max_length=1000, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="lead_comments")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"lead comment by {self.created_by.username.title()}"


class LeadFile(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="lead_files")
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE, related_name="files")
    file = models.FileField(upload_to="files/lead/")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="lead_files")
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Lead file by {self.created_by}"

lead/forms.py
from django import forms

from django.core.exceptions import ValidationError

from lead.models import Lead, Comment, LeadFile

from team.models import Team


class LeadCreateForm(forms.ModelForm):
    team = forms.ModelChoiceField(Team.objects.all())

    def __init__(self, user, *args, **kwargs):
        super(LeadCreateForm, self).__init__(*args, **kwargs)
        self.fields["team"].queryset = Team.objects.filter(created_by=user)
    class Meta:
        model = Lead
        fields = [
            'name',
            'email',
            'team',
            'description',
            'priority',
            'status'
        ]
    
    def clean_team(self):
        data = self.cleaned_data['team']
        if data.plan.max_leads <= data.leads.count():
            raise ValidationError(f"Lead limit Reached for team: {data}")
        return data

class LeadUpdateForm(forms.ModelForm):
    team = forms.ModelChoiceField(Team.objects.all())

    def __init__(self, user, *args, **kwargs):
        super(LeadUpdateForm, self).__init__(*args, **kwargs)
        self.fields["team"].queryset = Team.objects.filter(created_by=user)
    class Meta:
        model = Lead
        fields = [
            'name',
            'email',
            'team',
            'description',
            'priority',
            'status'
        ]


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ['file']

lead/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse

import csv

from django.urls import reverse_lazy, reverse

from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic import ListView, DetailView
from django.views.generic.detail import SingleObjectMixin
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.contrib.messages import success, error
from django.contrib.messages.views import SuccessMessageMixin

from django.db.models import Q

from lead.forms import LeadCreateForm, LeadUpdateForm, AddCommentForm, AddFileForm
from lead.models import Lead, LeadFile

from client.models import Client, Comment as ClientComment

# Create your views here.


class LeadCreateView(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    form_class = LeadCreateForm
    template_name = "lead/leadCreate.html"
    success_url = reverse_lazy("lead:leadList")
    success_message = "New Lead Created"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class LeadListView(LoginRequiredMixin, ListView):
    model = Lead
    context_object_name = "leads"
    template_name = "lead/leadList.html"

    def get_queryset(self):
        return Lead.objects.filter(Q(created_by = self.request.user) & Q(converted_into_clients=False))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["conv_leads"] = Lead.objects.filter(Q(created_by = self.request.user) & Q(converted_into_clients=True))
        return context



class GetComment(LoginRequiredMixin, DetailView):
    model = Lead
    context_object_name = "lead"
    template_name = "lead/leadDetail.html"
    
    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs["comment_form"] = AddCommentForm()
        kwargs["file_form"] = AddFileForm()
        return kwargs
    
    def get_queryset(self):
        return Lead.objects.filter(created_by=self.request.user, pk=self.kwargs['pk'])


class PostComment(SingleObjectMixin, LoginRequiredMixin, FormView):
    model = Lead
    form_class = AddCommentForm
    context_object_name = "lead"
    template_name = "lead/leadDetailView"

    def get_queryset(self):
        return Lead.objects.filter(created_by=self.request.user, pk=self.kwargs['pk'])
    
    def post(self, request, *args, **kwargs): # from SingleObjectMixin returns url paramater
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.lead = self.object
        comment.team = self.object.team
        comment.created_by = self.request.user
        comment.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse("lead:leadDetail", args=[self.object.id])


class LeadDetailView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        view = GetComment.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        view = PostComment.as_view()
        return view(request, *args, **kwargs)

class LeadDetailFileView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        fileUpload = AddFileForm(request.POST, request.FILES)
        if fileUpload.is_valid():
            lead = Lead.objects.get(created_by=request.user, pk=self.kwargs["pk"])
            file = fileUpload.save(commit=False)
            file.created_by = request.user
            file.team = lead.team
            file.lead = lead
            file.save()
            success(request, "Lead file uploaded")
        return redirect("lead:leadDetail", pk=self.kwargs['pk'])        

class LeadUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin ,UpdateView):
    model = Lead
    form_class = LeadUpdateForm
    context_object_name = "lead"
    template_name = "lead/leadUpdate.html"
    success_message = "Lead Updated Successfully"

    def test_func(self):
        self.object = self.get_object()
        return self.object.created_by == self.request.user and self.object.converted_into_clients == False

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs
    

class LeadDeleteView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = Lead
    template_name = "lead/leadDelete.html"
    context_object_name = "lead"
    success_message = "Lead Deleted Successfully"
    success_url = reverse_lazy("lead:leadList")

    def test_func(self):
        self.object = self.get_object()
        return self.object.created_by == self.request.user


class ConvertToClient(LoginRequiredMixin, SuccessMessageMixin, View):
    def get(self, request, *args, **kwargs):
        lead = get_object_or_404(Lead, created_by=request.user, pk=self.kwargs['pk'])
        if lead.team.plan.max_clients <= lead.team.clients.count():
            error(request, "Client Limit already reached")
            return redirect("lead:leadDetail", pk=lead.id)
        client = Client.objects.create(
            name=lead.name,
            email=lead.email,
            description=lead.description,
            created_by = request.user,
            team=lead.team
        )
        lead.converted_into_clients = True
        lead.save()

        comments = lead.comments.all()
        for comment in comments:
            ClientComment.objects.create(
                team = comment.team,
                client=client,
                created_by=comment.created_by,
                content=comment.content

            )
        success(request, f"successfully converted lead: {lead.name.title()} into client")
        return redirect("lead:leadList")
    

class LeadExportView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        leads = Lead.objects.filter(created_by=request.user, converted_into_clients=False)
        response = HttpResponse(
            content_type="text/csv",
            headers={
                "Content-Disposition":f"attachment; filename='{request.user}-leads.csv'"
            }
        )
        writer = csv.writer(response)
        writer.writerow([f"Leads of {request.user.username.title()}"])
        writer.writerow(['Lead','Description','Created by', 'Created at', 'Modified at'])
        for lead in leads:
            writer.writerow([lead.name, lead.description, lead.created_by, lead.created_at, lead.modified_at])
        return response

templates/lead/leadCreate.html
{% extends "base/base.html" %}
{% load tailwind_filters %}
{% block title %}Create New Lead{% endblock %}

{% block body %}
<div class="w-1/2 bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    <h1 class="text-2xl text-center mb-2 font-bold">Create New Lead</h1>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="py-4 px-8 bg-violet-400 rounded-xl text-white">Create</button>
    </form>
</div>
{% endblock %}

templates/lead/leadDelete.html
{% extends "base/base.html" %}
{% block title %}Delete: {{lead.name}}{% endblock %}

{% block body %}
<div class="w-1/2 bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    <h1 class="text-2xl text-center mb-2 font-bold">Delete lead: {{lead.name|title }}</h1>
    <form method="post">
        {% csrf_token %}
        <p class="mt-4 font-semibold">Do you want to delete this lead: {{lead.name|title}}?</p>
        <button type="submit" class="py-4 px-8 bt-4 rounded-xl bg-violet-400 text-white">Delete</button>
    </form>
</div>
{% endblock %}

templates/lead/leadDetail.html
{% extends "base/base.html" %}
{% load tailwind_filters %}
{% block title %}{{lead.name}}{% endblock %}

{% block body %}
<div class="flex space-x-4 px-6 py-6">
    <div>
        <div class="bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3 h-fit">
            {% if lead.converted_into_clients %}
            <div class="py-4 px-4 bg-violet-400 rounded-xl text-white">
                <h1 class="text-2xl font-bold">This lead has been converted into client</h1>
            </div>
            {% endif %}
            <h1 class="text-2xl font-bold text-center mb-2">
                {{lead.name|title}}
            </h1>
            {% if lead.description %}
                <p class="font-semibold">Description</p>
                <p>{{lead.description}}</p>
            {% endif %}
            <p class="font-semibold">Priority</p>
            <p class="mb-2">{{ lead.get_priority_display }}</p>
            
            <p class="font-semibold">Status</p>
            <p class="mb-2">{{ lead.get_status_display }}</p>
        
            <p class="font-semibold">Team</p>
            <p class="mb-2">{{ lead.team }}</p>
        
            <p class="font-semibold">Created At</p>
            <p class="mb-2">{{ lead.created_at|timesince }} ago</p>
        
            <p class="font-semibold">Modified At</p>
            <p class="mb-6">{{ lead.modified_at|timesince }} ago</p>
        
            <a href="{% url 'lead:leadList' %}" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Back to List</a>
            <a href="{% url 'lead:leadDelete' lead.id %}" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Delete</a>
            {% if not lead.converted_into_clients  %}
            <a href="{% url 'lead:leadUpdate' lead.id %}" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Update</a>
            <a href="{% url 'lead:leadToClient' lead.id %}" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Convert to Client</a>
            {% endif %}
        </div>
        <div>
            <div class="bg-violet-200 px-4 py-4 rounded-xl">
                <h1>Uploaded Files</h1>
            <ul>
                {% for file in lead.files.all %}
                    <li><a href="{{file.file.url}}">File {{forloop.counter}}</a></li>
                {% endfor %}
            </ul>
            </div>
            <div class="bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
                <h1 class="text-2xl font-bold">Upload New file</h1>
                <form action="{% url 'lead:leadUpload' lead.pk %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{file_form|crispy}}
                    <button type="submit" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Upload</button>
                </form>
            </div>
        </div>
    </div>
    
    <div class="w-1/2">
        <div class="bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
            <h1 class="text-2xl font-bold">Comments</h1>
            {% for comment in lead.comments.all %}
                <div class="flex justify-between bg-violet-300 py-4 px-4 rounded-xl m-1">
                    <div>
                        <p>{{comment.content}}</p>
                    </div>
                    <div>
                        <p>Created By: @{{comment.created_by|title}}, {{comment.created_at|timesince}} ago</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
            <h1 class="text-2xl font-bold">Add Comment</h1>
            <form method="post">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <button type="submit" class="bg-violet-400 text-white py-4 px-6 rounded-xl">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/lead/leadList.html
{% extends "base/base.html" %}
{% block title %}List of Leads{% endblock %}

{% block body %}
<div class="w-3/4 bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    <div class="flex justify-between">
        <h1 class="text-2xl">List of Leads</h1>
        <div>
            <a href="{% url 'lead:leadCreate' %}" class="py-4 px-6 bg-violet-600 rounded-xl text-white">Create Lead</a>
            <a href="{% url 'lead:leadExport' %}" class="py-4 px-6 bg-violet-600 rounded-xl text-white">Export Lead</a>
        </div>
    </div>
    <div class="mt-6 flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Team</p>
    </div>
    {% for lead in leads %}
        <a href="{{ lead.get_absolute_url}}">
            <div class="flex justify-between">
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{lead.name}}</p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{lead.priority}}</p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{lead.status}}</p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{lead.team}}</p>
            </div>
        </a>
    {% empty %}
    <p>There are no leads in the database </p>
    {% endfor %}

</div>

<div class="w-3/4 bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    <div class="flex justify-between">
        <h1 class="text-2xl">List of converted Leads</h1>
        <a href="{% url 'lead:leadCreate' %}" class="py-4 px-6 bg-violet-600 rounded-xl text-white">Create Lead</a>
    </div>
    <div class="mt-6 flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Team</p>
    </div>
    {% for conv_lead in conv_leads %}
        <a href="{{ conv_lead.get_absolute_url}}">
            <div class="flex justify-between">
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{conv_lead.name}}</p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{conv_lead.priority}}</p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{conv_lead.status}}</p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{conv_lead.team}}</p>
            </div>
        </a>
    {% empty %}
    <p>There are no converted leads in the database </p>
    {% endfor %}
    
</div>
{% endblock %}

templates/lead/leadUpdate.html
{% extends "base/base.html" %}
{% load tailwind_filters %}
{% block title %}Update :{{lead.name}}{% endblock %}

{% block body %}
<div class="w-1/2 bg-violet-200 rounded-xl px-6 py-6 ml-auto mt-3 mr-auto mb-3">
    <h1 class="text-2xl text-center font-bold mb-2">Update lead :{{lead.name|title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="py-4 px-8 bg-violet-400 text-white">Update</button>
    </form>
</div>
{% endblock %}